config/routes.rb
Rails.application.routes.draw do
  root 'users#home_page'
  resources :products
  resources :users
  resources :sessions
  delete '/sessions', to: 'sessions#destroy', as: :logout
  get '/vendor/products', to: 'products#vendor_products', as: 'vendor_products'
  get '/cart', to: 'products#show_cart', as: 'show_cart'
  post 'products/add_to_cart', to: 'products#add_to_cart', as: 'add_to_cart'
  delete '/cart_product/:id', to: 'products#remove_from_cart', as: 'remove_from_cart'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :user
  belongs_to :product
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user

  validates :name, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  ROLES = %w[vendor customer].freeze

  has_secure_password

  has_many :products
  has_many :cart_items

  validates :name, :email, :role, presence: true
  validates :role, presence: true, inclusion: { in: ROLES }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def authenticate_user!
    redirect_to root_path unless current_user
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

  def index
    @products = Product.all
  end

  def new
    @product = Product.new
  end

  def show_cart
    @cart_items = current_user.cart_items.includes(:product)
  end

  def create
    @products = Product.new(product_params)
    @products.user_id = current_user.id
    return unless @products.save

    redirect_to vendor_products_path
    flash[:success] = 'Product Created Succesfully'
  end

  def add_to_cart
    product = Product.find(params[:product_id])
    current_user.cart_items.create(product: product)
    redirect_to show_cart_path
  end

  def remove_from_cart
    cart_item = current_user.cart_items.find(params[:id])
    cart_item.destroy
    redirect_to show_cart_path
  end

  def vendor_products
    @products = current_user.products
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :product_type)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new; end

  def create
    user = User.find_by(email: params[:email])
    if user&.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def home_page; end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path
    else
      render :new
    end
  end

  def all_product
    @products = Product.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :role, :admin)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MiniCart</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
   <div class="parent-div">

<div>
  <%# flash.each do |key, message| %>
  <%# <div class="flash <%= key %>
    <%#= message %>
  <%# </div> %>
<%# end %>

<% if current_user %>
  <p class = "current_user">Welcome: <%= current_user.name  %> (<%= current_user.role  %>) </p>
   <%= link_to "Logout", logout_path, data: { turbo_method: :delete }, class: "logout-button" %>
   <% if current_user.role == "vendor" %>
       <%= link_to 'Create Product', new_product_path, class: "button product-button" %>
       <%= link_to 'View Product', vendor_products_path, class: "button product-button" %>
   <% end%>
   <% if current_user.role == "customer" %>
       <%= link_to 'View All Product', products_path, class: "button product-button" %>
       <%= link_to 'Your Cart', show_cart_path, class: "button product-button" %>
   <% end%>


<% end %>
</div>


<div class= "login-signup">
<% if !current_user %>
<%= link_to 'SignUp', new_user_path, class: "button" %>
<%= link_to 'Login', new_session_path, class: "button" %>
<% end%>
</div>
</div>
 <%= stylesheet_link_tag 'custom' %>

    <%= yield %>
  </body>
</html>

app/views/products/index.html.erb
<h1>All Products</h1>
<div class="product-cards">

<% @products.each do |product| %>
<div class="product-card">
    <h2>Name: <%= product.name %></h2>
    <p>Description: <%= product.description %></p>
    <p>Type: <%= product.product_type %></p>
    <%= button_to 'Add to Cart', add_to_cart_path(product_id: product.id), method: :post, class: "button" %>
  </div>
<% end %>
</div>

app/views/products/new.html.erb
<div class = "form-style">
<%= form_with model: @product, url: products_path, method: :post, class: "inner-form" do |form| %>
  <% if current_user.role == "vendor" %>
    <%= form.label :name %>
    <%= form.text_field :name %>

    <%= form.label :description %>
    <%= form.text_area :description %>

    <%= form.label :product_type %>
    <%= form.text_field :product_type %>

    <%= form.submit "Create Product" %>
  <% else %>
    <p>Only users with the vendor role can create products.</p>
  <% end %>
<% end %>

</div>

app/views/products/show_cart.html.erb
<h1>Your Cart</h1>
<% if @cart_items.any? %>
<div class="product-cards">
    <% @cart_items.each do |cart_item| %>
    <div class="product-card">
        <h2>Name: <%= cart_item.product.name %> </h2>
        <p>Description: <%= cart_item.product.description %> </p>
        <p>Type: <%=cart_item.product.product_type %> </p>
        <%= link_to 'Remove', remove_from_cart_path(cart_item.id), data: { turbo_method: :delete }, class: "button" %>
    </div>
    <% end %>
</div>
<% else %>
  <p>Your cart is empty.</p>
<% end %>

app/views/products/vendor_products.html.erb
<h1>Your Products</h1>

<div class="product-cards">
  <% @products.each do |product| %>
    <div class="product-card">
      <h2>Name: <%= product.name %></h2>
      <p>Description: <%= product.description %></p>
      <p>Type: <%= product.product_type %></p>
    </div>
  <% end %>
</div>

app/views/users/home_page.html.erb
<div class = "heading"><h1 > Welcome to MiniCart . Here you can buy sell products </h1>
  <%= image_tag 'home_page.jpg'  %>
</div>
<%= stylesheet_link_tag 'custom' %>

app/views/users/new.html.erb
<div class = "form-style">

<h1>Signup</h1>
<%= form_with model: @user, url: users_path, method: :post, class: "inner-form" do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :email %>
  <%= f.email_field :email %>

  <%= f.label :password %>
  <%= f.password_field :password %>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>

  <%= f.label :role %>
  <%= f.select :role, User::ROLES %>

  <%= f.submit "Signup" %>
<% end %>

</div>